In [4]:
import numpy as np
arr = np.array([1,2,3,4])

print(arr)

print(arr + 2)

arr2 = np.array([2,3,4,5])

print(arr2+arr)

#np.meam(arr) среднее значение



[1 2 3 4]
[3 4 5 6]
[3 5 7 9]


In [5]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a.ndim) # вывдит какой мерности массим 2-х мерный одномерный  и тд.
a = np.array([1,2,3,4])
print(a.ndim)

2
1


In [6]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a.shape)# количество столбцов и сколько елементов в каждой строке

(3, 4)


In [10]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a.size) # общее количество елементов

12


In [11]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a.dtype) # возвращает тип

int64


In [13]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a.diagonal()) # в скобках можно указать индекс начала диагонали


[ 1  6 11]


In [15]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a.sum())

78


In [17]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a.mean()) #возвращает средне арифметическое всех элементов массива
"""
a.mean
a.max
"""
a.argmin # значение с 0 индексом
a.argmax # значение с 11 индксом 

6.5


In [18]:
a = np.zeros((2,4), int) # задать массив, заполнить нулями
print(a) 

[[0 0 0 0]
 [0 0 0 0]]


In [19]:
a = np.ones((2, 3))
print(
    a
)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
a = np.array([
    [1, 2, 3, 4.0],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
    ])
b = np.copy(a)
print(b)

"""
a = np.array([
    [1, 2, 3, 4.0],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
    ])
b = np.array(a, copy=True)
print(b)
"""

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [21]:
a = np.eye(4) #создаёт квадратную матрицу
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
a = np.array([[1, 20, 0, 6],
[5, 4, 7, 8.0],
[9, 0, 110,0],
[2, 4, 5, 6]])
print(np.sin(a))
print()
print(np.cos(a))
print()
print(np.tan(a))
print()
print(np.sin(45))
print()
print(np.cos(90))
print()
print(np.tan(45))

[[ 0.84147098  0.91294525  0.         -0.2794155 ]
 [-0.95892427 -0.7568025   0.6569866   0.98935825]
 [ 0.41211849  0.         -0.04424268  0.        ]
 [ 0.90929743 -0.7568025  -0.95892427 -0.2794155 ]]

[[ 0.54030231  0.40808206  1.          0.96017029]
 [ 0.28366219 -0.65364362  0.75390225 -0.14550003]
 [-0.91113026  1.         -0.99902081  1.        ]
 [-0.41614684 -0.65364362  0.28366219  0.96017029]]

[[ 1.55740772  2.23716094  0.         -0.29100619]
 [-3.38051501  1.15782128  0.87144798 -6.79971146]
 [-0.45231566  0.          0.04428604  0.        ]
 [-2.18503986  1.15782128 -3.38051501 -0.29100619]]

0.8509035245341184

-0.4480736161291702

1.6197751905438615


In [25]:
a = np.array([[1, 20, 0, 6],
[5, 4, 7, 8.0],
[9, 0, 110,0],
[2, 4, 5, 6]])
print(np.sqrt(a))
print()
print(np.sqrt(25))

[[ 1.          4.47213595  0.          2.44948974]
 [ 2.23606798  2.          2.64575131  2.82842712]
 [ 3.          0.         10.48808848  0.        ]
 [ 1.41421356  2.          2.23606798  2.44948974]]

5.0


In [26]:
b = np.array([[2, 3, 5, 6],
[3, 2, 7, 9],
[2.3, 6, 6, 7.0101],
[2.5, 5, 4, 5.0]])
print(np.unique(b))

[2.     2.3    2.5    3.     4.     5.     6.     7.     7.0101 9.    ]


In [27]:
a = np.array([[1, 20, 3, 6],
[5, 4, 7, 8],
[9, 10, 110, 12],
[2, 4, 5, 6]])

print(np.sort(a)) #сортировка построчно

[[  1   3   6  20]
 [  4   5   7   8]
 [  9  10  12 110]
 [  2   4   5   6]]


In [28]:
a = np.array([[1, 20, 3, 6],
[5, 4, 7, 8],
[9, 10, 110, 12],
[2, 4, 5, 6]])
print(np.sort(a, 0)) #сортировка по столбцам

[[  1   4   3   6]
 [  2   4   5   6]
 [  5  10   7   8]
 [  9  20 110  12]]
